// This file was generated by the Finch-Resources module. Do not edit it directly.
package data

import "github.com/adm87/finch-resources/resources"

const (
	// ======================================================
	// Assets
	// ======================================================

	TilemapCharactersPacked resources.ResourceHandle = "tilemap-characters_packed" // assets/images/tilemap-characters_packed.png
	TilemapExampleA         resources.ResourceHandle = "tilemap-example-a"         // assets/tilemaps/tilemap-example-a.tmx
	TilemapPacked           resources.ResourceHandle = "tilemap_packed"            // assets/images/tilemap_packed.png
	TilesetCharacters       resources.ResourceHandle = "tileset-characters"        // assets/tilesets/tileset-characters.tsx
	TilesetTiles            resources.ResourceHandle = "tileset-tiles"             // assets/tilesets/tileset-tiles.tsx

)
