// This file was generated by the Finch-Resources module. Do not edit it directly.
package data

type ResourceKey string

const (
	// ======================================================
	// Assets
	// ======================================================
	TestTilemap         ResourceKey = "test_tilemap"
	TestTilemapInfinite ResourceKey = "test_tilemap_infinite"
	Tileset             ResourceKey = "tileset"
	TilesetImage        ResourceKey = "tileset_image"
	// ======================================================
	// Embedded
	// ======================================================
	Char0000 ResourceKey = "char_0000"
)
