// This file was generated by the Finch-Resources module. Do not edit it directly.
package data

const (
	// ======================================================
	// Assets
	// ======================================================

	// assets/tilemaps/test_tilemap.tmx
	TestTilemap string = "test_tilemap"

	// assets/tilemaps/test_tilemap_infinite.tmx
	TestTilemapInfinite string = "test_tilemap_infinite"

	// assets/tilesets/tileset.tsx
	Tileset string = "tileset"

	// assets/images/tileset_image.png
	TilesetImage string = "tileset_image"

	// ======================================================
	// Embedded
	// ======================================================

	// embedded/char_0000.png
	Char0000 string = "char_0000"
)
